const fs = require('fs');
const path = require('path');

// Resolve the API URL from environment variables, or use the Render default placeholder
let rawApiUrl =
  process.env.API_URL ||
  process.env.BACKEND_URL ||
  process.env.RENDER_EXTERNAL_URL ||
  'https://warehouse-marketplace-backend.onrender.com';

// Ensure the API URL ends with /api/v1
rawApiUrl = rawApiUrl.trim().replace(/\/+$/, '');
const apiUrl = rawApiUrl.endsWith('/api/v1') ? rawApiUrl : `${rawApiUrl}/api/v1`;

const targetDir = path.resolve(__dirname, '../src/environments');
const targetFile = path.join(targetDir, 'environment.prod.ts');

const envFileContent = `// Automatically generated by scripts/set-env.js during build
export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
};
`;

try {
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }
  fs.writeFileSync(targetFile, envFileContent, { encoding: 'utf8' });
  console.log(`[set-env] Successfully generated environment.prod.ts with apiUrl: ${apiUrl}`);
} catch (err) {
  console.error(`[set-env Error] Failed to generate environment.prod.ts:`, err);
  process.exit(1);
}
